version: 1
providers:
  - name: datadog-prod
    type: Datadog
    enabled: true
    settings:
      api_url: "https://api.datadoghq.com"
      api_key_env: "DD_API_KEY"
      app_key_env: "DD_APP_KEY"

  # Future:
  # - name: otel-local
  #   type: OtelCollector
  #   enabled: true
  #   settings:
  #     endpoint: "http://localhost:4318"
